all:
	g++ Agenda.h Agenda.cpp Contacto.cpp Contacto.h GestorDBFichero.cpp GestorDBFichero.h GestorDBInterfaz.cpp GestorDBInterfaz.h MenuTerminal.cpp MenuTerminal.h programaPrincipalAgenda.cpp -o programa-agenda.exe

